// Mocks generated by Mockito 5.0.11 from annotations
// in places/test/features/places/domain/usercases/get_google_place_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:multiple_result/multiple_result.dart' as _i2;
import 'package:places/core/error/failures.dart' as _i5;
import 'package:places/features/places/domain/entities/photo_entity.dart'
    as _i9;
import 'package:places/features/places/domain/entities/place_details_entity.dart'
    as _i8;
import 'package:places/features/places/domain/entities/place_entity.dart'
    as _i6;
import 'package:places/features/places/domain/entities/types.dart' as _i7;
import 'package:places/features/places/domain/repositories/google_place_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeResult<E, S> extends _i1.Fake implements _i2.Result<E, S> {}

/// A class which mocks [GooglePlaceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGooglePlaceRepository extends _i1.Mock
    implements _i3.GooglePlaceRepository {
  MockGooglePlaceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.Failure, List<_i6.PlaceEntity>>> getGooglePlace(
          _i7.PlaceType? type) =>
      (super.noSuchMethod(Invocation.method(#getGooglePlace, [type]),
              returnValue:
                  Future<_i2.Result<_i5.Failure, List<_i6.PlaceEntity>>>.value(
                      _FakeResult<_i5.Failure, List<_i6.PlaceEntity>>()))
          as _i4.Future<_i2.Result<_i5.Failure, List<_i6.PlaceEntity>>>);
  @override
  _i4.Future<_i2.Result<_i5.Failure, _i8.PlaceDetailsEntity>>
      getGooglePlaceDetails(String? placeId) => (super.noSuchMethod(
              Invocation.method(#getGooglePlaceDetails, [placeId]),
              returnValue:
                  Future<_i2.Result<_i5.Failure, _i8.PlaceDetailsEntity>>.value(
                      _FakeResult<_i5.Failure, _i8.PlaceDetailsEntity>()))
          as _i4.Future<_i2.Result<_i5.Failure, _i8.PlaceDetailsEntity>>);
  @override
  _i4.Future<_i2.Result<_i5.Failure, _i9.PhotoEntity>> getGooglePlacePhoto(
          {String? placeId,
          String? photoReference,
          String? maxWith,
          String? maxHeight}) =>
      (super.noSuchMethod(
          Invocation.method(#getGooglePlacePhoto, [], {
            #placeId: placeId,
            #photoReference: photoReference,
            #maxWith: maxWith,
            #maxHeight: maxHeight
          }),
          returnValue: Future<_i2.Result<_i5.Failure, _i9.PhotoEntity>>.value(
              _FakeResult<_i5.Failure, _i9.PhotoEntity>())) as _i4
          .Future<_i2.Result<_i5.Failure, _i9.PhotoEntity>>);
}
